export const LOGIN = 'user:login'
export const REGISTER = 'user:register'
export const ERROR = 'user:error'
export const LOGOUT = 'user:logout'
export const FACEBOOK_LOGIN = 'user:facebook'
export const REGISTER_ERROR = 'register:error'
export const CLEAR_MESS = 'mess:clear:user'